const PDFDocument = require('pdfkit');
const ExcelJS = require('exceljs');
const FIR = require('../models/FIR');
const Case = require('../models/Case');
const Crime = require('../models/Crime');
const Criminal = require('../models/Criminal');
const User = require('../models/User');
const Investigation = require('../models/Investigation');

/**
 * CSV String Escaper
 */
const escapeCSV = (value) => {
  if (value === null || value === undefined) return '""';
  const stringValue = String(value);
  if (stringValue.includes('"') || stringValue.includes(',') || stringValue.includes('\n') || stringValue.includes('\r')) {
    return `"${stringValue.replace(/"/g, '""')}"`;
  }
  return `"${stringValue}"`;
};

/**
 * Sanitize query parameters (handle undefined, null, empty strings, 'ALL', etc.)
 */
const sanitizeParam = (val) => {
  if (!val || val === 'undefined' || val === 'null' || String(val).trim() === '' || String(val).trim().toUpperCase() === 'ALL') {
    return undefined;
  }
  return String(val).trim();
};

/**
 * Helper to fetch accessible Case IDs for user role
 */
const getAccessibleCaseIds = async (user) => {
  if (user.role === 'ADMIN') {
    return null; // All cases accessible
  }

  const query = { isDeleted: false };
  if (user.role === 'OFFICER') {
    query.assignedOfficerId = user.id;
  } else if (user.role === 'VIEWER') {
    if (!user.supervisorOfficerId) return [];
    query.assignedOfficerId = user.supervisorOfficerId;
  }

  const cases = await Case.find(query).select('_id');
  return cases.map((c) => c._id);
};

/**
 * Helper for Date Range Query
 */
const buildDateRangeQuery = (field, dateFrom, dateTo) => {
  const from = sanitizeParam(dateFrom);
  const to = sanitizeParam(dateTo);
  const range = {};
  if (from) {
    const dFrom = new Date(from);
    if (!isNaN(dFrom.getTime())) {
      range.$gte = dFrom;
    }
  }
  if (to) {
    const dTo = new Date(to);
    if (!isNaN(dTo.getTime())) {
      dTo.setHours(23, 59, 59, 999);
      range.$lte = dTo;
    }
  }
  return Object.keys(range).length > 0 ? { [field]: range } : {};
};

/**
 * Helper to compute proportional column widths for PDF table
 */
const computePDFColumnWidths = (headers, totalWidth) => {
  const weightMap = {
    'FIR Number': 75,
    'Case Number': 75,
    'Crime ID': 65,
    'Linked FIR Number': 70,
    'Crime Classification': 65,
    'Crime Type': 65,
    'Category': 65,
    'Severity Level': 50,
    'Severity': 50,
    'Priority Level': 50,
    'Priority': 50,
    'Investigation Status': 75,
    'Status': 70,
    'Case Status': 70,
    'Complainant Name': 80,
    'Complainant': 80,
    'Complainant Contact': 65,
    'Contact': 65,
    'Incident Date': 55,
    'Case Opened Date': 55,
    'Case Closed Date': 55,
    'Registered Date': 55,
    'Opened Date': 55,
    'Incident Location': 90,
    'Location': 90,
    'Location / Scene': 90,
    'Assigned Investigating Officer': 85,
    'Assigned Officer Name': 85,
    'Investigating Officer': 85,
    'Officer': 80,
    'Officer Employee ID': 60,
    'Officer ID': 60,
    'Full Name': 85,
    'Aliases': 75,
    'Age': 35,
    'Gender': 45,
    'Physical Identifying Marks': 110,
    'Physical Marks': 110,
    'Registered Address': 110,
    'Associated Cases Count': 55,
    'Associated Cases': 55,
    'Brief Description': 130,
    'Summary / Notes': 130,
    'Description': 130,
  };

  const weights = headers.map((h) => weightMap[h] || 70);
  const totalWeight = weights.reduce((sum, w) => sum + w, 0);
  return weights.map((w) => (w / totalWeight) * totalWidth);
};

/**
 * Generate PDF Document Buffer
 */
const buildPDFBuffer = (title, headers, rows, user, filterDesc = '', summary = null) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        margin: 36,
        size: 'A4',
        layout: 'landscape',
        bufferPages: true,
      });

      const buffers = [];
      doc.on('data', (chunk) => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', reject);

      const pageWidth = doc.page.width - 72;

      // Header Banner
      doc.rect(36, 36, pageWidth, 54).fill('#0F172A');

      doc.fillColor('#FFFFFF')
        .fontSize(14)
        .font('Helvetica-Bold')
        .text('STATE POLICE DEPARTMENT — OFFICIAL RECORD DOSSIER', 48, 48);

      doc.fillColor('#94A3B8')
        .fontSize(9)
        .font('Helvetica')
        .text('CrimeTrack Law Enforcement Case Management & Intelligence Platform', 48, 66);

      // Report Title & Metadata
      let currentY = 104;
      doc.fillColor('#0F172A')
        .fontSize(16)
        .font('Helvetica-Bold')
        .text(title, 36, currentY);

      currentY += 22;
      doc.fillColor('#475569')
        .fontSize(9)
        .font('Helvetica')
        .text(`Generated: ${new Date().toLocaleString()}   |   Generated By: ${user.name} (${user.role})   |   ${filterDesc || 'Scope: All Filtered Records'}`, 36, currentY);

      // Summary KPI banner if provided
      if (summary) {
        currentY += 18;
        doc.rect(36, currentY, pageWidth, 28).fill('#F1F5F9');
        doc.fillColor('#1E293B')
          .fontSize(9)
          .font('Helvetica-Bold')
          .text(
            `Total Records: ${rows.length}   |   Total Cases: ${summary.totalCases || 0}   |   Resolved: ${summary.resolved || 0}   |   Clearance Rate: ${summary.resolutionRate || 0}%`,
            48,
            currentY + 9
          );
        currentY += 36;
      } else {
        currentY += 20;
      }

      // Compute proportional column widths and cumulative positions
      const colWidths = computePDFColumnWidths(headers, pageWidth);
      const colPositions = [0];
      for (let i = 0; i < colWidths.length - 1; i++) {
        colPositions.push(colPositions[i] + colWidths[i]);
      }

      // Compute dynamic header height
      doc.fontSize(8).font('Helvetica-Bold');
      let maxHeaderH = 22;
      headers.forEach((h, idx) => {
        const textH = doc.heightOfString(h, { width: colWidths[idx] - 8, lineGap: 1 });
        if (textH + 8 > maxHeaderH) maxHeaderH = textH + 8;
      });
      const headerHeight = Math.min(maxHeaderH, 30);

      const renderHeaderRow = (y) => {
        doc.rect(36, y, pageWidth, headerHeight).fill('#2563EB');
        doc.fillColor('#FFFFFF').fontSize(8).font('Helvetica-Bold');

        headers.forEach((header, i) => {
          doc.text(header, 36 + colPositions[i] + 4, y + 5, {
            width: colWidths[i] - 8,
            height: headerHeight - 6,
            ellipsis: true,
            lineGap: 1,
          });
        });
      };

      // Draw initial Header Row
      renderHeaderRow(currentY);
      currentY += headerHeight;

      // Draw Data Rows
      rows.forEach((row, rowIndex) => {
        // Measure dynamic row height based on text content
        doc.fontSize(7.5).font('Helvetica');
        let maxCellH = 22;
        row.forEach((cell, idx) => {
          const text = String(cell || 'N/A');
          const textH = doc.heightOfString(text, { width: colWidths[idx] - 8, lineGap: 1 });
          if (textH + 8 > maxCellH) maxCellH = textH + 8;
        });
        const rowHeight = Math.min(Math.max(22, maxCellH), 48);

        // Page break check
        if (currentY + rowHeight > doc.page.height - 45) {
          doc.addPage({ layout: 'landscape', margin: 36 });
          currentY = 40;
          renderHeaderRow(currentY);
          currentY += headerHeight;
        }

        // Alternating background
        const bgColor = rowIndex % 2 === 0 ? '#F8FAFC' : '#FFFFFF';
        doc.rect(36, currentY, pageWidth, rowHeight).fill(bgColor);

        // Cell borders
        doc.rect(36, currentY, pageWidth, rowHeight).stroke('#CBD5E1');

        // Draw individual cells with bounded height and ellipsis
        doc.fillColor('#0F172A').fontSize(7.5).font('Helvetica');
        row.forEach((cell, cellIndex) => {
          doc.text(String(cell || 'N/A'), 36 + colPositions[cellIndex] + 4, currentY + 5, {
            width: colWidths[cellIndex] - 8,
            height: rowHeight - 6,
            ellipsis: true,
            lineGap: 1,
          });
        });

        currentY += rowHeight;
      });

      // Pagination Footers
      const range = doc.bufferedPageRange();
      for (let i = 0; i < range.count; i++) {
        doc.switchToPage(i);
        doc.fillColor('#94A3B8')
          .fontSize(8)
          .font('Helvetica')
          .text(
            `Page ${i + 1} of ${range.count}  •  Confidential Law Enforcement Document  •  CrimeTrack System`,
            36,
            doc.page.height - 28,
            { align: 'center', width: pageWidth }
          );
      }

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};

/**
 * Generate Excel Workbook Buffer
 */
const buildExcelBuffer = async (sheetName, title, headers, rows, user, filterDesc = '', summary = null) => {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'CrimeTrack Police Management System';
  workbook.created = new Date();

  const worksheet = workbook.addWorksheet(sheetName, {
    views: [{ showGridLines: true }],
  });

  // Title Block
  worksheet.mergeCells('A1', `${String.fromCharCode(64 + headers.length)}1`);
  const titleRow = worksheet.getCell('A1');
  titleRow.value = `STATE POLICE DEPARTMENT — ${title.toUpperCase()}`;
  titleRow.font = { name: 'Arial', size: 14, bold: true, color: { argb: 'FFFFFFFF' } };
  titleRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0F172A' } };
  titleRow.alignment = { vertical: 'middle', horizontal: 'center' };
  worksheet.getRow(1).height = 30;

  // Metadata Row
  worksheet.mergeCells('A2', `${String.fromCharCode(64 + headers.length)}2`);
  const metaRow = worksheet.getCell('A2');
  metaRow.value = `Generated: ${new Date().toLocaleString()} | Generated By: ${user.name} (${user.role}) | ${filterDesc || 'Full Authorized Scope'}`;
  metaRow.font = { name: 'Arial', size: 9, italic: true, color: { argb: 'FF475569' } };
  metaRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF1F5F9' } };
  metaRow.alignment = { vertical: 'middle', horizontal: 'center' };
  worksheet.getRow(2).height = 20;

  let startRow = 4;

  if (summary) {
    worksheet.mergeCells('A3', `${String.fromCharCode(64 + headers.length)}3`);
    const sumRow = worksheet.getCell('A3');
    sumRow.value = `Summary KPIs: Total Records = ${rows.length}, Total Cases = ${summary.totalCases || 0}, Solved Cases = ${summary.solvedCases || 0}, Clearance Rate = ${summary.resolutionRate || 0}%`;
    sumRow.font = { name: 'Arial', size: 9, bold: true, color: { argb: 'FF1E293B' } };
    sumRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE2E8F0' } };
    sumRow.alignment = { vertical: 'middle', horizontal: 'center' };
    worksheet.getRow(3).height = 20;
    startRow = 5;
  }

  // Table Headers
  const headerRow = worksheet.getRow(startRow);
  headerRow.values = headers;
  headerRow.height = 24;
  headerRow.eachCell((cell) => {
    cell.font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FFFFFFFF' } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF2563EB' } };
    cell.alignment = { vertical: 'middle', horizontal: 'center' };
    cell.border = {
      top: { style: 'thin', color: { argb: 'FFCBD5E1' } },
      left: { style: 'thin', color: { argb: 'FFCBD5E1' } },
      bottom: { style: 'medium', color: { argb: 'FF0F172A' } },
      right: { style: 'thin', color: { argb: 'FFCBD5E1' } },
    };
  });

  // Table Rows
  rows.forEach((rowData, idx) => {
    const row = worksheet.addRow(rowData);
    row.height = 20;
    const isEven = idx % 2 === 0;
    row.eachCell((cell) => {
      cell.font = { name: 'Arial', size: 9 };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: isEven ? 'FFF8FAFC' : 'FFFFFFFF' },
      };
      cell.border = {
        top: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        left: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        right: { style: 'thin', color: { argb: 'FFE2E8F0' } },
      };
      cell.alignment = { vertical: 'middle' };
    });
  });

  // Auto-fit column widths
  worksheet.columns.forEach((column) => {
    let maxLength = 12;
    column.eachCell({ includeEmpty: true }, (cell) => {
      const valLength = cell.value ? String(cell.value).length : 0;
      if (valLength > maxLength) {
        maxLength = Math.min(valLength, 45);
      }
    });
    column.width = maxLength + 3;
  });

  return await workbook.xlsx.writeBuffer();
};

/**
 * Generate FIR Report (CSV / JSON / PDF / EXCEL)
 */
const generateFIRReport = async (filters = {}, user, format = 'csv') => {
  const { dateFrom, dateTo, crimeType, assignedOfficerId } = filters;
  const query = { isDeleted: false, ...buildDateRangeQuery('incidentDate', dateFrom, dateTo) };

  // Scoping
  if (user.role === 'OFFICER') {
    query.assignedOfficerId = user.id;
  } else if (user.role === 'VIEWER') {
    if (!user.supervisorOfficerId) query.assignedOfficerId = null;
    else query.assignedOfficerId = user.supervisorOfficerId;
  } else if (user.role === 'ADMIN') {
    const sanitizedOfficer = sanitizeParam(assignedOfficerId);
    if (sanitizedOfficer) query.assignedOfficerId = sanitizedOfficer;
  }

  const sanitizedCrimeType = sanitizeParam(crimeType);
  if (sanitizedCrimeType) {
    query.crimeType = sanitizedCrimeType.toUpperCase();
  }

  const firs = await FIR.find(query)
    .populate('assignedOfficerId', 'name email employeeId role')
    .sort({ incidentDate: -1 });

  if (format === 'json') {
    return firs;
  }

  const headers = [
    'FIR Number',
    'Crime Classification',
    'Complainant Name',
    'Complainant Contact',
    'Incident Date',
    'Incident Location',
    'Assigned Officer Name',
    'Officer Employee ID',
    'Registered Date',
    'Brief Description',
  ];

  const rawRows = firs.map((f) => [
    f.firNumber || 'N/A',
    f.crimeType || 'N/A',
    f.complainantName || 'N/A',
    f.complainantPhone || 'N/A',
    f.incidentDate ? new Date(f.incidentDate).toLocaleDateString() : 'N/A',
    f.incidentPlace || 'N/A',
    f.assignedOfficerId?.name || 'Unassigned',
    f.assignedOfficerId?.employeeId || 'N/A',
    f.createdAt ? new Date(f.createdAt).toLocaleDateString() : 'N/A',
    f.description || 'N/A',
  ]);

  if (format === 'pdf') {
    const filterDesc = `Crime Category: ${sanitizedCrimeType || 'All Categories'} | Date Range: ${sanitizeParam(dateFrom) || 'Start'} to ${sanitizeParam(dateTo) || 'Present'}`;
    const summary = await getReportSummary(filters, user);
    return await buildPDFBuffer('FIR Complaints Ledger Report', headers, rawRows, user, filterDesc, summary);
  }

  if (format === 'excel' || format === 'xlsx') {
    const filterDesc = `Crime Category: ${sanitizedCrimeType || 'All Categories'} | Date Range: ${sanitizeParam(dateFrom) || 'Start'} to ${sanitizeParam(dateTo) || 'Present'}`;
    const summary = await getReportSummary(filters, user);
    return await buildExcelBuffer('FIR Complaints', 'FIR Complaints Ledger Report', headers, rawRows, user, filterDesc, summary);
  }

  // Default CSV
  const csvRows = rawRows.map((r) => r.map((c) => escapeCSV(c)).join(','));
  return [headers.join(','), ...csvRows].join('\r\n');
};

/**
 * Generate Case Clearance & Investigation Report (CSV / JSON / PDF / EXCEL)
 */
const generateCaseReport = async (filters = {}, user, format = 'csv') => {
  const { dateFrom, dateTo, status, priority, assignedOfficerId } = filters;
  const query = { isDeleted: false, ...buildDateRangeQuery('createdAt', dateFrom, dateTo) };

  // Scoping
  if (user.role === 'OFFICER') {
    query.assignedOfficerId = user.id;
  } else if (user.role === 'VIEWER') {
    if (!user.supervisorOfficerId) query.assignedOfficerId = null;
    else query.assignedOfficerId = user.supervisorOfficerId;
  } else if (user.role === 'ADMIN') {
    const sanitizedOfficer = sanitizeParam(assignedOfficerId);
    if (sanitizedOfficer) query.assignedOfficerId = sanitizedOfficer;
  }

  const sanitizedStatus = sanitizeParam(status);
  if (sanitizedStatus) {
    query.status = sanitizedStatus.toUpperCase();
  }

  const sanitizedPriority = sanitizeParam(priority);
  if (sanitizedPriority) {
    query.priority = sanitizedPriority.toUpperCase();
  }

  const cases = await Case.find(query)
    .populate('firId', 'firNumber crimeType incidentPlace')
    .populate('assignedOfficerId', 'name email employeeId role')
    .sort({ createdAt: -1 });

  if (format === 'json') {
    return cases;
  }

  const headers = [
    'Case Number',
    'Investigation Status',
    'Priority Level',
    'Linked FIR Number',
    'Crime Type',
    'Incident Location',
    'Assigned Investigating Officer',
    'Officer Employee ID',
    'Case Opened Date',
    'Case Closed Date',
    'Summary / Notes',
  ];

  const rawRows = cases.map((c) => [
    c.caseNumber || 'N/A',
    c.status || 'N/A',
    c.priority || 'N/A',
    c.firId?.firNumber || 'N/A',
    c.firId?.crimeType || 'N/A',
    c.firId?.incidentPlace || 'N/A',
    c.assignedOfficerId?.name || 'Unassigned',
    c.assignedOfficerId?.employeeId || 'N/A',
    c.createdAt ? new Date(c.createdAt).toLocaleDateString() : 'N/A',
    c.closedAt ? new Date(c.closedAt).toLocaleDateString() : 'N/A',
    c.summary || 'N/A',
  ]);

  if (format === 'pdf') {
    const filterDesc = `Status: ${sanitizedStatus || 'All'} | Priority: ${sanitizedPriority || 'All'} | Dates: ${sanitizeParam(dateFrom) || 'Start'} to ${sanitizeParam(dateTo) || 'Present'}`;
    const summary = await getReportSummary(filters, user);
    return await buildPDFBuffer('Case Clearance & Investigation Dossier', headers, rawRows, user, filterDesc, summary);
  }

  if (format === 'excel' || format === 'xlsx') {
    const filterDesc = `Status: ${sanitizedStatus || 'All'} | Priority: ${sanitizedPriority || 'All'} | Dates: ${sanitizeParam(dateFrom) || 'Start'} to ${sanitizeParam(dateTo) || 'Present'}`;
    const summary = await getReportSummary(filters, user);
    return await buildExcelBuffer('Case Dossier', 'Case Clearance & Investigation Dossier', headers, rawRows, user, filterDesc, summary);
  }

  // Default CSV
  const csvRows = rawRows.map((r) => r.map((c) => escapeCSV(c)).join(','));
  return [headers.join(','), ...csvRows].join('\r\n');
};

/**
 * Generate Crime Classification Report (CSV / JSON / PDF / EXCEL)
 */
const generateCrimeReport = async (filters = {}, user, format = 'csv') => {
  const { dateFrom, dateTo, crimeType, severity } = filters;
  const query = { isDeleted: false, ...buildDateRangeQuery('crimeDate', dateFrom, dateTo) };

  const accessibleCaseIds = await getAccessibleCaseIds(user);
  if (accessibleCaseIds !== null) {
    query.caseId = { $in: accessibleCaseIds };
  }

  const sanitizedCrimeType = sanitizeParam(crimeType);
  if (sanitizedCrimeType) {
    query.crimeType = sanitizedCrimeType.toUpperCase();
  }

  const sanitizedSeverity = sanitizeParam(severity);
  if (sanitizedSeverity) {
    query.severity = sanitizedSeverity.toUpperCase();
  }

  const crimes = await Crime.find(query)
    .populate({
      path: 'caseId',
      select: 'caseNumber status assignedOfficerId',
      populate: { path: 'assignedOfficerId', select: 'name employeeId' },
    })
    .sort({ crimeDate: -1 });

  if (format === 'json') {
    return crimes;
  }

  const headers = [
    'Crime ID',
    'Crime Type',
    'Severity Level',
    'Location / Scene',
    'Incident Date',
    'Associated Case Number',
    'Case Status',
    'Investigating Officer',
    'Description',
  ];

  const rawRows = crimes.map((cr) => [
    cr._id.toString(),
    cr.crimeType || 'N/A',
    cr.severity || 'N/A',
    cr.location || 'N/A',
    cr.crimeDate ? new Date(cr.crimeDate).toLocaleDateString() : 'N/A',
    cr.caseId?.caseNumber || 'N/A',
    cr.caseId?.status || 'N/A',
    cr.caseId?.assignedOfficerId?.name || 'N/A',
    cr.description || 'N/A',
  ]);

  if (format === 'pdf') {
    const filterDesc = `Crime Category: ${sanitizedCrimeType || 'All'} | Severity: ${sanitizedSeverity || 'All'} | Dates: ${sanitizeParam(dateFrom) || 'Start'} to ${sanitizeParam(dateTo) || 'Present'}`;
    return await buildPDFBuffer('Crime Incidents & Classification Report', headers, rawRows, user, filterDesc);
  }

  if (format === 'excel' || format === 'xlsx') {
    const filterDesc = `Crime Category: ${sanitizedCrimeType || 'All'} | Severity: ${sanitizedSeverity || 'All'} | Dates: ${sanitizeParam(dateFrom) || 'Start'} to ${sanitizeParam(dateTo) || 'Present'}`;
    return await buildExcelBuffer('Crime Incidents', 'Crime Incidents & Classification Report', headers, rawRows, user, filterDesc);
  }

  // Default CSV
  const csvRows = rawRows.map((r) => r.map((c) => escapeCSV(c)).join(','));
  return [headers.join(','), ...csvRows].join('\r\n');
};

/**
 * Generate Criminal Master Directory Report (CSV / JSON / PDF / EXCEL)
 */
const generateCriminalReport = async (filters = {}, user, format = 'csv') => {
  const query = { isDeleted: false };

  const accessibleCaseIds = await getAccessibleCaseIds(user);
  if (accessibleCaseIds !== null) {
    query.associatedCaseIds = { $in: accessibleCaseIds };
  }

  const criminals = await Criminal.find(query).sort({ name: 1 });

  if (format === 'json') {
    return criminals;
  }

  const headers = [
    'Full Name',
    'Aliases',
    'Age',
    'Gender',
    'Physical Identifying Marks',
    'Registered Address',
    'Associated Cases Count',
  ];

  const rawRows = criminals.map((cr) => [
    cr.name || 'N/A',
    cr.aliases && cr.aliases.length > 0 ? cr.aliases.join(', ') : 'None',
    cr.age !== undefined && cr.age !== null ? String(cr.age) : 'N/A',
    cr.gender || 'N/A',
    cr.identifyingMarks || 'None',
    cr.address || 'N/A',
    String(cr.associatedCaseIds ? cr.associatedCaseIds.length : 0),
  ]);

  if (format === 'pdf') {
    return await buildPDFBuffer('Criminal Master Directory Report', headers, rawRows, user, 'Scope: Authorized Criminal Records');
  }

  if (format === 'excel' || format === 'xlsx') {
    return await buildExcelBuffer('Criminal Records', 'Criminal Master Directory Report', headers, rawRows, user, 'Scope: Authorized Criminal Records');
  }

  // Default CSV
  const csvRows = rawRows.map((r) => r.map((c) => escapeCSV(c)).join(','));
  return [headers.join(','), ...csvRows].join('\r\n');
};

/**
 * Get Filtered Report Summary Metrics
 */
const getReportSummary = async (filters = {}, user) => {
  const { dateFrom, dateTo } = filters;
  const firDateQuery = buildDateRangeQuery('incidentDate', dateFrom, dateTo);
  const caseDateQuery = buildDateRangeQuery('createdAt', dateFrom, dateTo);

  const firQuery = { isDeleted: false, ...firDateQuery };
  const caseQuery = { isDeleted: false, ...caseDateQuery };

  if (user.role === 'OFFICER') {
    firQuery.assignedOfficerId = user.id;
    caseQuery.assignedOfficerId = user.id;
  } else if (user.role === 'VIEWER') {
    if (user.supervisorOfficerId) {
      firQuery.assignedOfficerId = user.supervisorOfficerId;
      caseQuery.assignedOfficerId = user.supervisorOfficerId;
    }
  }

  const [totalFIRs, totalCases, solvedCases, closedCases] = await Promise.all([
    FIR.countDocuments(firQuery),
    Case.countDocuments(caseQuery),
    Case.countDocuments({ ...caseQuery, status: 'SOLVED' }),
    Case.countDocuments({ ...caseQuery, status: 'CLOSED' }),
  ]);

  const resolved = solvedCases + closedCases;
  const resolutionRate = totalCases > 0 ? Math.round((resolved / totalCases) * 100) : 0;

  return {
    totalFIRs,
    totalCases,
    solvedCases,
    closedCases,
    resolved,
    resolutionRate,
    period: {
      from: sanitizeParam(dateFrom) || 'All time',
      to: sanitizeParam(dateTo) || 'Present',
    },
  };
};

module.exports = {
  generateFIRReport,
  generateCaseReport,
  generateCrimeReport,
  generateCriminalReport,
  getReportSummary,
};

